I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "renpy/common/00start.rpy", line 83, in _init_language
    renpy.change_language(language)
  File "game/screens.rpy", line 137, in <module>
    background Fit("bg_startingscreen.png", xalign=0.5, yalign=0.5)
NameError: name 'Fit' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Volumes/renpy-8.2.3-sdk 1/renpy-8.2.3-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/Volumes/renpy-8.2.3-sdk 1/renpy-8.2.3-sdk/renpy/main.py", line 637, in main
    run(restart)
  File "/Volumes/renpy-8.2.3-sdk 1/renpy-8.2.3-sdk/renpy/main.py", line 75, in run
    renpy.translation.init_translation()
  File "/Volumes/renpy-8.2.3-sdk 1/renpy-8.2.3-sdk/renpy/translation/__init__.py", line 664, in init_translation
    renpy.store._init_language() # type: ignore
  File "renpy/common/00start.rpy", line 83, in _init_language
    renpy.change_language(language)
  File "/Volumes/renpy-8.2.3-sdk 1/renpy-8.2.3-sdk/renpy/translation/__init__.py", line 758, in change_language
    new_change_language(tl, language)
  File "/Volumes/renpy-8.2.3-sdk 1/renpy-8.2.3-sdk/renpy/translation/__init__.py", line 710, in new_change_language
    i.apply()
  File "/Volumes/renpy-8.2.3-sdk 1/renpy-8.2.3-sdk/renpy/ast.py", line 2787, in apply
    value = renpy.python.py_eval(expr)
  File "/Volumes/renpy-8.2.3-sdk 1/renpy-8.2.3-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Volumes/renpy-8.2.3-sdk 1/renpy-8.2.3-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/screens.rpy", line 137, in <module>
    background Fit("bg_startingscreen.png", xalign=0.5, yalign=0.5)
NameError: name 'Fit' is not defined

macOS-12.6.8-arm64-arm-64bit arm64
Ren'Py 8.2.3.24061702
Magic Girl Incubator 1.0
Wed Aug 21 16:55:52 2024
